### PR TITLE
Added quick set-up instructions

### PR DESCRIPTION
**Pull request by AlbertoGP**

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
Hi Alberto,

Thanks for your additions!
Just this weekend I thought I should a TL:DR/How to use section in the readme, guess you were faster ;)

One small question, is there a specific reason you use an environment variable for the container name?

Best regards,
Simon

**Comment by AlbertoGP** [comment]
Simon van der Veldt wrote: (02/12/13 22:09)

> [...]
> One small question, is there a specific reason you use an environment
> variable for the container name?

   Nothing important, just to make it stand out a bit so I don't forget
to change it, and to use it again in the path for the network
configuration. I imagine I would want to copy and paste in a hurry
when setting up a new container.

   I thought about using <name> instead, which would be shorter, but
then I can't just paste it as is. In some user interfaces (like the
phone) moving the cursor around is a pain so although I don't need
to do that often, I write my installation notes in a way that does
not require getting to the middle of a line and changing things there.

   The main point is that I had to look around a bit to figure out
exactly which file I had to download because it was not obvious
whether lxc-debian-wheezy-robvdhoeven was Rob's original file or
your modified version, and then look inside it to find the root
password.

   If you'd rather use <name> without the variable or something
else, just let me know and I'll adapt it. Or maybe you prefer to
write it from scratch in your style.
   In any case thanks. This thing was driving me mad until I found
the bug report. I can't believe the package is still broken in such
a dumb way.

##    Cheers,

```
 Alberto González Palomo
 http://sentido-labs.com
 Im Flürchen 39a, D-66133 Saarbrücken, Deutschland
```

**Comment by simonvanderveldt** [comment]
Thanks for the additional info. I understand your point that it still takes too much figuring out to get started, we should try to make that easier for everybody. Simply having decent documentation can do wonders in that regard :)

There are some things I want to add/change to the text (I want to stay in line with what's in the Debian wiki), but I will do so based on your text. I've just merged the pull request and will add the additions this evening.

Thanks for your help and if you have any more suggestions or issues let me know.

P.S. You should get a line saying `Root password is 'root', please change !` when creating a new container ;)

**Comment by AlbertoGP** [comment]
Simon van der Veldt wrote: (03/12/13 20:33)

> [...]
> P.S. You should get a line saying |Root password is 'root', please
> change !| when creating a new container ;)

   :-D  You are right, it's right there.

##    Cheers,

```
 Alberto González Palomo
 http://sentido-labs.com
 Im Flürchen 39a, D-66133 Saarbrücken, Deutschland
```

**Pull request merged**
